/**
 * Which municipality does an outdated Gemeindeschlüssel belong to today?
 *
 * The plant register (MaStR) keeps the key a unit was registered under. When a
 * municipality merges, dissolves or changes district, Destatis assigns a new
 * key — the register does not follow. Measured 18.09.2026: 292 outdated keys
 * still carried plants, among them Hanau (kreisfrei since 01.01.2026, old key
 * 06435014 → 06415000). Its atlas page showed zero plants for 98,000 residents
 * while the numbers sat on a key no page reads. No error, no red test.
 *
 * The mapping comes from the official Destatis list of territorial changes
 * ("Namens-, Grenz- und Schlüsselnummernänderungen"), generated by
 * scripts/destatis-gebietsaenderungen.ts into ags-nachfolger-daten.json. Never
 * hand-edit that file and never guess a successor from a name: two municipalities
 * called Obergeckler existed side by side in the register.
 */
import DATEN from "./ags-nachfolger-daten.json";

export type Nachfolge = {
  /** Current 8-digit key the old one maps to (one step, not resolved). */
  neu: string;
  /** Statistical effective date, YYYY-MM-DD. */
  seit: string;
  /**
   * The old municipality was split across several successors. Its plants go to
   * the one that took most residents (then most area) — the register does not
   * tell us where inside the old area a unit stands.
   */
  aufgeteilt?: true;
};

export type NachfolgeTabelle = Record<string, Nachfolge>;

const TABELLE = (DATEN as { nachfolger: NachfolgeTabelle }).nachfolger;

/** One row of the Destatis change list, Gemeinde level only. */
export type Gebietsaenderung = {
  kennziffer: string;
  alt: string;
  neu: string;
  /** Änderungsart as printed: "1" dissolved, "2" partial transfer, "3" key change, "4" name. */
  art: string;
  flaecheQm: number;
  einwohner: number;
  /** Statistical effective date, YYYY-MM-DD. */
  seit: string;
};

const AGS = /^\d{8}$/;

/**
 * Builds the one-step mapping old key → successor from the change list.
 *
 * Only "1" (dissolved) and "3" (key change) move a whole municipality. "2" is a
 * partial area transfer: the giving municipality keeps existing under its key,
 * so remapping it would move all its plants for a few hectares.
 *
 * Chronology matters: a key that RECEIVES territory at a later date is alive
 * again at that date, and an earlier mapping away from it must not survive —
 * otherwise a reused key would send today's plants to a municipality that
 * absorbed its predecessor decades ago.
 */
export function nachfolgerAusAenderungen(zeilen: Gebietsaenderung[]): NachfolgeTabelle {
  const sortiert = [...zeilen]
    .filter((z) => AGS.test(z.alt) && AGS.test(z.neu))
    .sort((a, b) => a.seit.localeCompare(b.seit) || a.kennziffer.localeCompare(b.kennziffer));

  const out: NachfolgeTabelle = {};
  // Per change (Kennziffer) and old key, collect all targets to decide splits.
  type Kandidat = { neu: string; einwohner: number; flaecheQm: number };
  let i = 0;
  while (i < sortiert.length) {
    const seit = sortiert[i].seit;
    const tag: Gebietsaenderung[] = [];
    while (i < sortiert.length && sortiert[i].seit === seit) tag.push(sortiert[i++]);

    // Everything that receives territory on this day is alive on this day.
    for (const z of tag) if (z.neu !== z.alt) delete out[z.neu];

    const ganz = new Map<string, Kandidat[]>();
    for (const z of tag) {
      const arten: string[] = z.art.match(/\d/g) ?? [];
      if (!arten.includes("1") && !arten.includes("3")) continue;
      if (z.neu === z.alt) continue;
      const liste = ganz.get(z.alt) ?? [];
      liste.push({ neu: z.neu, einwohner: z.einwohner, flaecheQm: z.flaecheQm });
      ganz.set(z.alt, liste);
    }
    for (const [alt, kandidaten] of ganz) {
      const ziele = new Map<string, Kandidat>();
      for (const k of kandidaten) {
        const da = ziele.get(k.neu);
        if (da) {
          da.einwohner += k.einwohner;
          da.flaecheQm += k.flaecheQm;
        } else ziele.set(k.neu, { ...k });
      }
      const bester = [...ziele.values()].sort(
        (a, b) => b.einwohner - a.einwohner || b.flaecheQm - a.flaecheQm || a.neu.localeCompare(b.neu),
      )[0];
      out[alt] = ziele.size > 1 ? { neu: bester.neu, seit, aufgeteilt: true } : { neu: bester.neu, seit };
    }
  }
  return out;
}

/**
 * The current key for a (possibly outdated) 8-digit Gemeindeschlüssel.
 * Follows chains (A → B → C); an unknown key is returned unchanged.
 */
export function aktuellerGemeindeschluessel(ags: string, tabelle: NachfolgeTabelle = TABELLE): string {
  let aktuell = ags;
  const gesehen = new Set<string>();
  while (tabelle[aktuell] && !gesehen.has(aktuell)) {
    gesehen.add(aktuell);
    aktuell = tabelle[aktuell].neu;
  }
  return aktuell;
}
