import data from './story-city-data.json';
import type { StoryConcept } from './story-konzepte';
const source = {label:'Marktstammdatenregister · Gesamtdatenexport 10. September 2026',url:'https://download.marktstammdatenregister.de/Gesamtdatenexport_20260910_26.1.zip'};
const fundingTrier={label:'Stadt Trier: Förderzeitraum Juli 2024 bis März 2026',url:'https://www.trier.de/leben-in-trier/klima-umwelt/klimaschutz/erneuerbare-energien/solarenergie/13861.Foerderung-von-Balkonsolaranlagen.html'};
const fundingNidda={label:'Stadt Nidda: verstärkte Förderung ab Februar 2023',url:'https://www.nidda.de/news/news-archiv/2023/1-quartal-2023/pv-foerderung/'};
const number=(n:number)=>n.toLocaleString('de-DE');
function sum(id:string,segment:string,year?:string,field:'count'|'kwp'='count') {return data.rows.filter(r=>r.region_id===id&&r.segment===segment&&(!year||r.month.startsWith(year))).reduce((s,r)=>s+r[field],0);}
function years(id:string,segment:string){return ['2021','2022','2023','2024','2025'].map(label=>({label,value:sum(id,segment,label)}));}
function base(id:string,town:string):StoryConcept{return {id,town,label:'',kind:'bars',title:'',teaser:'',period:'Stand 10. Sept. 2026',evidence:'Registerexport 10. Sept. 2026 · Gestaltung zur Abnahme',values:[],unit:'',copy:[],social:'',widget:'Aktuellen Zubau auf der Gemeindeseite verlinken. Die Story bleibt ein datierter Rückblick.',widgetCta:'Aktuellen Zubau ansehen',seo:'Lokale Originalauswertung mit nachvollziehbarem Zeitraum und eigener Story-Adresse. Teaser auf der Gemeindeseite, vollständige Einordnung im Detail.',beforeRelease:'Gestaltung und Wortlaut abnehmen. Gezählt werden heute aktive Registereinheiten nach Inbetriebnahme; Nachmeldungen und Stilllegungen können spätere Auswertungen verändern.',sources:[source]};}
function finish(s:StoryConcept){s.social=`${s.title}\n\n${s.teaser}\n\n${s.copy.map(p=>p.text).join('\n\n')}\n\nQuelle: Marktstammdatenregister, eigene Auswertung. Stand 10. September 2026.`;return s;}
export function roofStory(town:string,values:{label:string;value:number}[]):StoryConcept {
 const latest=values.at(-1)!;const previous=values.at(-2)!;
 const change=Math.round(Math.abs(latest.value-previous.value)/previous.value*100);
 const direction=latest.value<previous.value?'weniger':'mehr';
 const peak=values.reduce((best,v)=>v.value>best.value?v:best);
 const story=finish({...base(`${town}-gebaeude`,town),label:'Gebäudeanlagen im Jahresvergleich',kind:'columns',
 title:`${town}: ${change} % ${direction} neue Gebäude-Solaranlagen`,
 teaser:`${latest.value} Anlagen mit Inbetriebnahme ${latest.label} sind erfasst – nach ${previous.value} im Jahr ${previous.label}. Der Vergleich zeigt die Veränderung des jährlichen Zubaus.`,
 values,unit:'Gebäude-Solaranlagen · Inbetriebnahmen pro Jahr',
 comparisonLabel:`Vollständige Kalenderjahre ${values[0].label}–${latest.label}. Hauptvergleich: ${latest.label} gegenüber ${previous.label}.`,
 copy:[{heading:'Der Verlauf hinter der Zahl',text:`Unter den gezeigten Jahren liegt ${peak.label} mit ${peak.value} Anlagen vorne. ${latest.label} waren es ${latest.value}. Gezählt werden Anlagen, nicht ihre Leistung: Wenige große Anlagen können mehr Modulleistung hinzufügen als viele kleine.`},
 {heading:'Was das für den Ausbau bedeutet',text:direction==='weniger'?'Ein geringerer jährlicher Zubau bedeutet nicht, dass Solaranlagen verschwinden. Er beschreibt, wie viele Anlagen eines neuen Inbetriebnahmejahrgangs heute im Register stehen. Über Stilllegungen oder die Veränderung des Gesamtbestands sagt dieser Vergleich nichts aus.':'Mehr Inbetriebnahmen zeigen einen stärkeren Anlagenzubau. Ob auch die neu installierte Leistung wächst, muss separat betrachtet werden.'}],
 beforeRelease:'Lokalen Entwurf abnehmen. Grundlage: aktive Gebäudeanlagen im Registerexport vom 10. September 2026; keine Eigentümerklassifikation. Nachmeldungen und Stilllegungen können spätere Auswertungen verändern.'});
 story.social=`${town}: ${change} % ${direction} neue Gebäude-Solaranlagen ${latest.label}.\n\n${latest.value} Inbetriebnahmen stehen ${previous.value} im Jahr ${previous.label} gegenüber. ${direction==='weniger'?'Der jährliche Zubau fällt kleiner aus – das bedeutet nicht, dass der Anlagenbestand schrumpft.':'Damit steigt die Zahl der neu in Betrieb genommenen Anlagen.'}\n\nDie Grafik zeigt ${values[0].label} bis ${latest.label}. Gebäudeanlagen können auf Wohnhäusern ebenso wie auf anderen Gebäuden stehen. Gezählt sind heute aktive Registereinheiten nach Inbetriebnahmejahr, keine Haushalte.\n\nQuelle: Marktstammdatenregister · eigene Auswertung · Stand 10. Sept. 2026.`;
 return story;
}
function roof(id:string,town:string){return roofStory(town,years(id,'gebaeude'));}
function participation(id:string,town:string){const b=sum(id,'steckersolar'),d=sum(id,'gebaeude');const bc=Math.round(b/(b+d)*1000)/10,bp=Math.round(sum(id,'steckersolar',undefined,'kwp')/(sum(id,'steckersolar',undefined,'kwp')+sum(id,'gebaeude',undefined,'kwp'))*1000)/10;return finish({...base(`${town}-beteiligung`,town),label:'Anlagenzahl und Leistung',kind:'shares',title:`Viele kleine Anlagen, ein anderer Maßstab`,teaser:`${number(b)} Balkonkraftwerke sind in ${town} erfasst. Zusammen mit den ${number(d)} Gebäudeanlagen betrachtet, stellen sie ${number(bc)} % der Anlagen – und ${number(bp)} % der Modulleistung.`,values:[{label:'Anteil an der Anlagenzahl',value:bc},{label:'Anteil an der Modulleistung',value:bp}],unit:'Balkonkraftwerke im Vergleich zu Gebäudeanlagen',comparisonLabel:'Bezugsmenge: aktive Gebäudeanlagen und Balkonkraftwerke; Freiflächen ausgeschlossen.',copy:[{heading:'Zwei Perspektiven auf denselben Ausbau',text:'Beim Zählen wiegt ein Balkonkraftwerk genauso viel wie eine große Gebäudeanlage. Beim Leistungsvergleich zählt dagegen die installierte Modulgröße. Deshalb unterscheiden sich die beiden Anteile so deutlich.'},{heading:'Was die kleinen Anlagen beitragen',text:'Balkonkraftwerke eröffnen Solarstrom auch dort, wo keine große Dachanlage möglich ist. Die Registerzahl entspricht aber weder der Zahl beteiligter Menschen noch der Zahl versorgter Haushalte.'}],widget:'Passend als aktuelles Bestandswidget: Anlagenzahl und Leistung getrennt zeigen. Die Story erklärt den Unterschied einmal verständlich.',widgetCta:'Anlagenbestand ansehen'});}
const trier=base('Trier-foerderphase','Trier');
const timeline=[];for(let y=2023;y<=2026;y++)for(let m=1;m<=12;m++){const label=`${y}-${String(m).padStart(2,'0')}`;if(label>'2026-05')break;timeline.push({label,value:data.rows.find(r=>r.region_id==='07211000'&&r.segment==='steckersolar'&&r.month===label)?.count??0});}
const funding=finish({...trier,label:'Balkonförderung und Zubau',kind:'timeline' as const,title:'Zwei starke Monate rund um Triers Balkonförderung',teaser:'118 Balkonkraftwerke im August 2024, 116 im März 2026: Zwei auffällige Monate liegen kurz nach Beginn und am Ende der städtischen Förderung.',values:timeline,unit:'Balkonkraftwerke nach Inbetriebnahmemonat',highlightedMonths:['2024-08','2026-03'],event:{month:'2024-07',label:'Förderbeginn Juli 2024'},eventEnd:'2026-03',chartSummary:'August 2024: 118 · März 2026: 116',comparisonLabel:'Gezeigt: Januar 2023–Mai 2026. Historie seit 2019 geprüft.',sources:[source,fundingTrier],copy:[{heading:'Der Förderzeitraum im Verlauf',text:'Die Stadt förderte Balkonkraftwerke von Juli 2024 bis zum 31. März 2026. Im August 2024 und im März 2026 liegen die beiden höchsten Monatswerte der ausgewerteten Trierer Reihe bis Mai 2026.'},{heading:'Ein Zusammenhang, kein Wirkungsnachweis',text:'Die Balken zählen Inbetriebnahmen, keine Förderanträge. Preisentwicklung, bundesweite Veränderungen und Nachmeldungen können ebenfalls beitragen. Ob und wie viele dieser Anlagen bezuschusst wurden, lässt sich aus dem Register nicht ablesen.'}],beforeRelease:trier.beforeRelease+' Fördertermine sind durch die Stadt belegt. Eine Förderwirkung wird nicht behauptet.'});
const nidda=finish({...base('Nidda-niveau','Nidda'),label:'Dauerhaft höherer Zubau',kind:'columns' as const,title:'Nidda: Drei Jahre mit mehr als 120 neuen Balkonkraftwerken',teaser:'2023 waren es 122, 2024 dann 129 und 2025 weitere 131. Nach dem Sprung von zehn Anlagen im Jahr 2022 bleibt der Zubau auf einem deutlich höheren Niveau.',values:years('06440016','steckersolar'),unit:'Balkonkraftwerke nach Inbetriebnahmejahr',comparisonLabel:'Vergleich: vollständige Kalenderjahre 2021–2025',sources:[source,fundingNidda],copy:[{heading:'Ein neues Niveau statt eines Einzelpeaks',text:'Der auffällige Befund ist nicht ein einzelner Monat: In drei aufeinanderfolgenden Jahren sind jeweils mehr als 120 Inbetriebnahmen erfasst. Die Jahresansicht zeigt diese Beständigkeit besser als ein herausgegriffener Spitzenmonat.'},{heading:'Die Förderung als lokaler Kontext',text:'Nidda setzte seine Förderung im Februar 2023 mit aufgestocktem Budget und einem Schwerpunkt für Mini-PV fort. Die zeitliche Nähe passt zur Entwicklung, beweist aber nicht, dass die Förderung den Anstieg verursacht hat.'}]});
// Each entry represents a separate editorial question, not a separate metric from the same event.
function trierStories():StoryConcept[] {
 const id='07211000',town='Trier';
 const annual=(segment:string,field:'count'|'kwp'='count')=>['2021','2022','2023','2024','2025'].map(label=>({label,value:Math.round(sum(id,segment,label,field)*100)/100}));
 const make=(key:string,label:string,title:string,teaser:string,values:StoryConcept['values'],unit:string,comparison:string,heading:string,text:string,kind:StoryConcept['kind']='columns')=>finish({...base(`Trier-${key}`,town),label,title,teaser,values,unit,comparisonLabel:comparison,kind,copy:[{heading,text},{heading:'So wurden die Zahlen ermittelt',text:'Gezählt werden die im Registerexport vom 10. September 2026 aktiven Einheiten nach ihrem Inbetriebnahmedatum. Das ist keine historische Bestandsaufnahme. Nachmeldungen und Stilllegungen können spätere Auswertungen verändern.'}]});
 const b22=sum(id,'steckersolar','2022'),b23=sum(id,'steckersolar','2023'),b24=sum(id,'steckersolar','2024'),b25=sum(id,'steckersolar','2025');
 const p24=sum(id,'steckersolar','2024','kwp'),p25=sum(id,'steckersolar','2025','kwp');
 const partial=(y:string)=>data.rows.filter(r=>r.region_id===id&&r.segment==='steckersolar'&&r.month>=`${y}-01`&&r.month<=`${y}-05`).reduce((n,r)=>n+r.count,0);
 const a=partial('2025'),b=partial('2026');
 const total=data.rows.filter(r=>r.region_id===id).reduce((n,r)=>n+r.kwp,0),free=sum(id,'freiflaeche',undefined,'kwp');
 const totalCount=data.rows.filter(r=>r.region_id===id).reduce((n,r)=>n+r.count,0),freeCount=sum(id,'freiflaeche');
 return [
 make('balkon-2026','Balkonkraftwerke im Vorjahresvergleich',`Trier: ${Math.round((b/a-1)*100)} % mehr neue Balkonkraftwerke bis Mai`,`${b} Inbetriebnahmen von Januar bis Mai 2026 stehen ${a} im selben Zeitraum 2025 gegenüber.`,[{label:'Jan.–Mai 2025',value:a},{label:'Jan.–Mai 2026',value:b}],'Balkonkraftwerke · Anlagen','Vergleich: 1. Januar–31. Mai 2026 gegenüber 1. Januar–31. Mai 2025.','Gleiche Monate, ein höherer Zubau','Beide Balken decken dieselben fünf Kalendermonate ab. Der Vergleich vermeidet damit, ein begonnenes Jahr mit einem vollen Jahr zu vergleichen. Die jüngsten Monate Juni bis September bleiben wegen möglicher Nachmeldungen außen vor. Daraus folgt noch keine Prognose für das Gesamtjahr.'),
 roof(id,town),funding,
 make('balkon-modulgroesse','Anlagenzahl und Modulgröße','Weniger neue Balkonkraftwerke, mehr Modulleistung',`2025 sind ${b25} neue Balkonkraftwerke erfasst, nach ${b24} im Vorjahr. Ihre gemeinsame Modulleistung steigt trotzdem von ${number(Math.round(p24))} auf ${number(Math.round(p25))} kWp.`,[{label:'2024',value:Math.round(p24/b24*1000)},{label:'2025',value:Math.round(p25/b25*1000)}],'Mittlere Modulleistung pro neuer Anlage · Wp','Vergleich: vollständige Inbetriebnahmejahrgänge 2024 und 2025.','Die durchschnittliche Anlage wird größer','Die Modulleistung je erfasster Anlage erklärt, warum Anlagenzahl und Gesamtleistung in unterschiedliche Richtungen laufen können. Angegeben ist die Nennleistung der Module, nicht die Wechselrichterleistung oder die tatsächlich eingespeiste Leistung. Ein höherer Wert bedeutet deshalb nicht automatisch mehr Einspeisung.'),
 make('balkon-2024','Balkonkraftwerke im Jahresverlauf',`${b24} neue Balkonkraftwerke: Triers starker Jahrgang 2024`,`Nach ${b23} Anlagen 2023 steigt die Zahl auf ${b24} im Jahr 2024. 2025 bleibt sie mit ${b25} deutlich über dem Niveau von 2023.`,annual('steckersolar'),'Balkonkraftwerke · Inbetriebnahmen pro Jahr','Vergleich: vollständige Kalenderjahre 2021–2025.','Ein Sprung, der im Jahresverlauf sichtbar bleibt',`Der Jahresblick zeigt mehr als einen einzelnen Spitzenmonat: Zwischen 2022 (${b22} Anlagen) und 2024 (${b24}) steigt die Zahl deutlich. Auch der folgende Jahrgang bleibt auf einem höheren Niveau. Eine Ursache lässt sich allein aus den Registerzahlen nicht bestimmen.`),
 make('gebaeude-2023','Gebäudeanlagen: Rückblick auf 2023','2023 war Triers stärkstes Gebäude-Solarjahr seit 2000',`${sum(id,'gebaeude','2023')} Inbetriebnahmen sind für 2023 erfasst, nach ${sum(id,'gebaeude','2022')} im Vorjahr. Kein anderer vollständiger Jahrgang von 2000 bis 2025 erreicht diesen Wert.`,Array.from({length:26},(_,i)=>({label:String(2000+i),value:sum(id,'gebaeude',String(2000+i))})),'Gebäudeanlagen · Inbetriebnahmen pro Jahr','Vergleich: vollständige Kalenderjahre 2000–2025.','Anlagen auf unterschiedlichen Gebäuden','Die Gebäude-Kategorie umfasst Wohnhäuser ebenso wie andere Gebäude. Der Rekord bezieht sich auf die Zahl heute aktiver Registereinheiten nach Inbetriebnahmejahr; er ist weder ein Rekord privater Hausbesitzer noch eine Aussage über den historischen Gesamtbestand.'),
 make('freiflaechen-anteil','Freiflächen im Gesamtbestand',`Wenige Freiflächenanlagen, ${Math.round(free/total*100)} % der Solarleistung`,`${freeCount} Freiflächeneinheiten stehen ${totalCount} Solareinheiten insgesamt gegenüber. Zusammen bringen sie ${number(Math.round(free/1000*10)/10)} MWp Modulleistung mit.`,[{label:'Anteil an allen Anlagen',value:Math.round(freeCount/totalCount*1000)/10},{label:'Anteil an der gesamten Modulleistung',value:Math.round(free/total*1000)/10}],'Anteile in Prozent','Bezugsmenge: alle aktiven Solareinheiten in Trier am Exportstand, einschließlich Gebäude, Balkonkraftwerke und sonstiger Anlagen.','Warum Anzahl allein nicht genügt','Beim Zählen erhält jede Registereinheit das gleiche Gewicht. Für die installierte Leistung ist dagegen ihre Größe entscheidend. Der Vergleich erklärt, warum wenige große Anlagen die Leistungsbilanz prägen können. Die Einheitenzahl ist nicht gleichbedeutend mit der Zahl eigenständiger Solarparks.','bars'),
 participation(id,town)
 ];
}
export const CITY_STORY_SETS:Record<string,StoryConcept[]>={Trier:trierStories(),Nidda:[nidda,roof('06440016','Nidda'),participation('06440016','Nidda')]};
