import {contactStateDigest} from '../../scripts/lib/contact-state-digest';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {it,expect} from 'vitest';
import {hash} from '../../scripts/lib/contact-workflow-store';import {requireContactComparison} from '../../scripts/lib/contact-comparison-gate';
it('rejects unproven improvements, changed original evidence and unlisted recipients before sending',()=>{
 const b=mkdtempSync(join(tmpdir(),'contact-compare-'));try{const w=join(b,'workflow');mkdirSync(w);const input=join(b,'input.json'),record=join(b,'record.json'),source=join(b,'original.html'),reportPath=join(b,'comparison.json');writeFileSync(input,'baseline');writeFileSync(source,'original');
 const write=(p:string,d:unknown)=>writeFileSync(p,JSON.stringify(d));write(join(w,'current-municipal-scope.json'),{items:[{currentMunicipalityId:'1',inventoryOrganizationId:'1'}]});write(join(b,'inventory.json'),{targets:[{organization_id:'1',dataset:'kommunen',audit:{inputPath:input}}]});write(record,{stateDigest:contactStateDigest(b,w,{dataset:'kommunen',organization_id:'1',audit:{inputPath:input}}),sourceManifest:[{valid:true,path:source,digest:hash(readFileSync(source))}]});
 const selection=join(b,'selection.json');write(selection,{kommunen:[{region_id:'1',rollen_email:null}]});
 const r={selectionBaseline:{kind:'saved-contact-selection',path:selection,digest:hash(readFileSync(selection))},approvedForUse:false,verdicts:{better:1,equivalent:0,worse:0,unresolved:0,'not-evaluated':0},lostProvenContacts:0,population:1,evaluated:1,scopeDigest:hash(readFileSync(join(w,'current-municipal-scope.json'))),inventoryDigest:hash(readFileSync(join(b,'inventory.json'))),rows:[{municipalityId:'1',baselineSelectionFound:true,baselineEmails:[],verdict:'better',current:true,sourceChecksComplete:true,baselineDigest:hash(readFileSync(input)),recordPath:record,recordDigest:hash(readFileSync(record)),gained:['person@town.de'],retained:[],lost:[],unresolvedBaseline:[],unsupportedSelected:[]}]};const recipient=[{organizationId:'1',email:'person@town.de'}];write(reportPath,r);expect(()=>requireContactComparison(w,reportPath,recipient)).toThrow('Verbesserung');r.approvedForUse=true;write(reportPath,r);expect(requireContactComparison(w,reportPath,recipient).approvedForUse).toBe(true);expect(()=>requireContactComparison(w,reportPath,[{organizationId:'1',email:'other@town.de'}])).toThrow('Empfänger');write(selection,{kommunen:[{region_id:'1',rollen_email:'old@town.de'}]});expect(()=>requireContactComparison(w,reportPath,recipient)).toThrow('Kontaktauswahl');write(selection,{kommunen:[{region_id:'1',rollen_email:null}]});const observations=join(b,'supplemental','1','observations');mkdirSync(observations,{recursive:true});writeFileSync(join(observations,'new.json'),'{}');expect(()=>requireContactComparison(w,reportPath,recipient)).toThrow('Neue Kontaktbelege');rmSync(join(b,'supplemental'),{recursive:true});writeFileSync(source,'changed');expect(()=>requireContactComparison(w,reportPath,recipient)).toThrow('Kontaktquelle');
 }finally{rmSync(b,{recursive:true,force:true});}
});
it('wires the comparison check before SMTP construction in the real sender',()=>{const s=readFileSync('scripts/kommunen-versand.ts','utf8').split('async function sendenIntern')[1];expect(s.indexOf('requireContactComparison(')).toBeGreaterThan(0);expect(s.indexOf('requireContactComparison(')).toBeLessThan(s.indexOf('await baueTransport()'));});
