import {readFileSync,writeFileSync,readdirSync,existsSync} from 'node:fs';
import {solarMonth} from '../lib/story-monthly-solar';
import {energyYear} from '../lib/story-energy-year';
const id=process.argv[2];
if(!/^\d{8}$/.test(id??''))throw Error('Pass a municipality ID');
const report=JSON.parse(readFileSync(`scripts/.cache/story-discovery/${id}.json`,'utf8'));
const root='scripts/.cache/story-ranking-month/sources';
const raw=JSON.parse(readFileSync(`${root}/${readdirSync(root).filter(f=>f.endsWith('.json')).sort().at(-1)}`,'utf8'));
const city=(Array.isArray(raw)?raw:raw.stats).find((r:{regionId:string})=>r.regionId===id);
if(!city||!Number.isFinite(city.windKwpLy))throw Error('No wind baseline');
const detail=JSON.parse(readFileSync(`scripts/.cache/bnetza/story-history-${report.sourceDate}/cities/${id}.json`,'utf8'));
const monthSource=JSON.parse(readFileSync(`scripts/.cache/story-radial/${id}-month.json`,'utf8'));
const yearSource=JSON.parse(readFileSync(`scripts/.cache/story-radial/${id}-year.json`,'utf8'));
const year=Number(yearSource.weather.hourly.time[0].slice(0,4));
const month=monthSource.weather.hourly.time.at(-1).slice(0,7);
const retrievedAt=new Date().toISOString();
const monthly={...solarMonth(monthSource.weather,detail.daily,month,report.sourceDate,retrievedAt,monthSource.sourceUrl),town:report.name};
const solarKwp=detail.daily.filter((r:{day:string;segment:string})=>r.day<`${year+1}-01-01`&&['gebaeude','freiflaeche','steckersolar','sonstige'].includes(r.segment)).reduce((s:number,r:{kwp:number})=>s+r.kwp,0);
const annual=energyYear(yearSource.weather,{town:report.name,year,solarKwp,windKw:city.windKwpLy,sourceDate:report.sourceDate,retrievedAt,sourceUrl:yearSource.sourceUrl});
const path='lib/story-radial-city-data.json';
const registry=existsSync(path)?JSON.parse(readFileSync(path,'utf8')):{};
registry[id]={monthly,annual};writeFileSync(path,JSON.stringify(registry));
console.log({town:report.name,month,days:monthly.days.length,monthlyMwh:monthly.totalMwh,year,solarKwp,windKw:annual.windKw,annualDays:annual.days.length});
