// GENERATED by scripts/build-gemeinde-geo.mjs — do not edit by hand.
// A Landkreis (key, 5-digit AGS) that geographically encloses a kreisfreie
// Stadt (value, 5-digit Kreis AGS) sitting in its hole. Used to draw the city
// into the Landkreis map bundle AND to add its value to that Kreis's choropleth.
export const ENCLOSED_CITIES: Record<string, string> = {
  "12071": "12052",
  "15088": "15002",
  "16071": "16055",
  "07235": "07211",
  "07340": "07317",
  "08125": "08121",
  "08216": "08211",
  "09187": "09163",
  "09274": "09261",
  "09278": "09263",
  "09371": "09361",
  "09374": "09363",
  "09375": "09362",
  "09471": "09461",
  "09472": "09462",
  "09473": "09463",
  "09475": "09464",
  "09571": "09561",
  "09678": "09662",
  "09679": "09663",
  "09777": "09762",
  "09780": "09763"
};
